### ISSUE TITLE
分片下载大文件200多MB，出现 “i/o timeout”

### ISSUE THREAD

**Issue by xunchangguo** [aliyun/aliyun-oss-go-sdk#10]
参数设置connectTimeoutSec=30，readWriteTimeout=120，分片大小：5M，Checkpoint=false
错误信息如下：
read tcp 198.9.4.207:53567->101.201.182.67:80: i/o timeout

另：通过“OSS控制台客户端(Windows)”下载正常

**Comment by xunchangguo** [comment]
补充下：
通过“OSS控制台客户端(Windows)”下载完成后的文件和用SDK下载出现 i/o timeout后的已经下载的文件对比发现，大小是一样的，用2进制比较工具比较，内容也是一样的。
怀疑：实际文件大小和通过接口获取的不一致，通过接口获取的文件大小大

**Comment by xunchangguo** [comment]
有时候，出现“unexpected EOF”，只要出现了错误，协程不退出，导致文件被占用，下载最新版本sdk，说是解决了协程不退出问题，试了，问题依旧啊，没有解决啊！

**Comment by baiyubin** [comment]
read  ... i/o timeout 是网络超时，分片下载出错后，下载的文件是无效，这点需要优化。请问什么情况下出现 unexpected EOF ？

**Comment by xunchangguo** [comment]
这么久了，总算有个回复的了。不过我也是只能“呵呵”了，最终还是都得靠自己啊。自己修改代码，解决了。
1、协程不退出，使用sync.WaitGroup解决，错误代码：
for completed < len(parts) {
.............................
select {
case <-results:
    completed++
    ps[part.Index] = part
case err = <-failed:
    close(die)
    return err
}
2、unexpected EOF ，出错代码
_, err = fd.Seek(part.Start, os.SEEK_SET)
if err != nil {
    failed <- err
    break
}
_, err = io.Copy(fd, rd)
if err != nil {
    failed <- err
    break
}
解决方式，可参照AWS SDK的实现方式和思路
