### ISSUE TITLE
支持context.Context

### ISSUE THREAD

**Issue by swagerebus** [aliyun/aliyun-oss-go-sdk#100]
现在主流都是一个参数传context.Context, 用于取消请求或者设置超时

是否考虑支持一下?

**Comment by rmrf** [comment]
同问，没有 context， 跟其他golang 项目集成是个大问题

**Comment by hangzws** [comment]
context要go 1.7版本才支持的吧，sdk要考虑到支持各种版本，目前不支持。

**Comment by rmrf** [comment]
> context要go 1.7版本才支持的吧，sdk要考虑到支持各种版本，目前不支持。

golang 的 context 是很重要的一个升级，尤其对于 http 相关调用，对OSS来说也很重要，尤其是主流的开源项目基本都升级了。 如果考虑兼容性的话， 个人认为这个“兼容”其实更加重要一些。

**Comment by hangzws** [comment]
@rmrf 欢迎提交pr
