### ISSUE TITLE
上传后回调通知

### ISSUE THREAD

**Issue by chalvern** [aliyun/aliyun-oss-go-sdk#102]
请问Go的sdk中如何实现上传后回调通知？

其他语言都有demo，Golang这边sdk里没有写这部分内容。

**Comment by hangzws** [comment]
多谢反馈，目前还不支持这个功能，已经在计划排期中了，欢迎提交pr。

**Comment by hangzws** [comment]
已更新

**Comment by JeffreyBool** [comment]
服务端签名直传并设置上传回调 zzhi支持lme吗
