### ISSUE TITLE
提供图片处理接口

### ISSUE THREAD

**Issue by kavimaluskam** [aliyun/aliyun-oss-go-sdk#109]
Node.js: https://www.alibabacloud.com/help/zh/doc-detail/50039.html?spm=a2c5t.11065259.1996646101.searchclickresult.475a2450GwMF7j

1. `bucket.go` 的 `DoGetObject`, `params`被hardcode成 empty map了
2. `option.go` 的 `Process`, 寫成HTTP Header的大寫, 不能用在query param上 ( https://github.com/aliyun/aliyun-oss-go-sdk/issues/95)

> 参考: https://github.com/aliyun/aliyun-oss-go-sdk/issues/80

**Comment by hangzws** [comment]
多谢反馈，我们在下一个版本会修改这个问题。

**Comment by hangzws** [comment]
以及合入ipv6分支，经过一段时间的测试验证，我们很快会合入master。
