### ISSUE TITLE
useless error return value

### ISSUE THREAD

**Issue by xujihui1985** [aliyun/aliyun-oss-go-sdk#116]
https://github.com/aliyun/aliyun-oss-go-sdk/blob/master/oss/client.go#L76

```
func (client Client) Bucket(bucketName string) (*Bucket, error) {
	return &Bucket{
		client,
		bucketName,
	}, nil
}
```

I thought this error return value is useless if it must be nil

**Comment by hangzws** [comment]
It is true that there is no need to return an error code in this place. However, this place has little impact. We do not intend to fix this issue, because there are already lots of users in use, and there may be compatibility issues after the upgrade.

**Comment by xujihui1985** [comment]
agree, issue closed
