### ISSUE TITLE
处理缩略图并下载时遇到oss.process("image/resize....")无效的解决

### ISSUE THREAD

**Issue by chenshandong** [aliyun/aliyun-oss-go-sdk#117]
一、修改X-Oss-Process为小写x-oss-process
二、修改bucket.go文件DoGetObject方法中的 params的赋值
将params := map[string]interface{}{} 修改为 params, _ := getRawParams(options)

**Comment by aidenliu** [comment]
经测试方案二无法解决此问题

**Comment by hangzws** [comment]
谢谢你们提出的宝贵已经，修改代码已经合入分支ipv6, 测试没问题会合入master并发布。

**Comment by zhuxianglong** [comment]
这个问题啥时候处理好呀
