### ISSUE TITLE
How do we get the content length of file ?

### ISSUE THREAD

**Issue by thomas-lee** [aliyun/aliyun-oss-go-sdk#122]
Sorry, I am new to golang. I have some questions.

Now I have tried to get GetObject from the bucket method(oss) and it now only returns the io.ReadCloser. And I can get the file but fail to get the file size, because i will act like proxy server to return the file from my http server and thus need to set the content-length in header.

Do you know how to get content length of file or file size ?

I saw in the bucket.go, it will process like in method DoGetObject
`resp.Body = ioutil.NopCloser(TeeReader(resp.Body, crcCalc, contentLen, listener, nil))`

And return Response.Body to GetObject method.

Is it possible to expose the contentLen too ?

Or it needs us to have further process to read/parse it in order to get the file size ?

Thanks

**Comment by hangzws** [comment]
good question, you can checkout the branch ipv6 and the new getobject api, it is now support get the content length.

**Comment by hangzws** [comment]
we will merge the pr to master soon.
