### ISSUE TITLE
Do we have any API to create the image style?

### ISSUE THREAD

**Issue by thomas-lee** [aliyun/aliyun-oss-go-sdk#123]
There is a document talking about Image Style (https://www.alibabacloud.com/help/doc-detail/48884.htm).

Do you know if any API we can manage the image style without access OSS console?

As a result, we can control the Style access rules manually after enabled original image protection.

Thanks.

**Comment by hangzws** [comment]
branch ipv6 has support get object with process style, you can use the GetObject API.
example ：
`response, err := bucket.GetObject(objectName, Process("image/format,png"))`

We will update the documentation after the code is merged into the master.

**Comment by thomas-lee** [comment]
I mean to create a new style by API, so that it will be a combination of styles because we can't access the image with processing parameters after enabled image protection.

```
http://bucket.<endpoint>/object?x-oss-process=style/<StyleName>
```

Thanks

**Comment by thomas-lee** [comment]
we will plan to create a new image use this API
https://www.alibabacloud.com/help/zh/doc-detail/55811.htm
