### ISSUE TITLE
Do we have the support to handle POST with saveAs ?

### ISSUE THREAD

**Issue by thomas-lee** [aliyun/aliyun-oss-go-sdk#125]
In the document, it said we can set with the x-oss-process and then save as a new picture in a bucket.

https://www.alibabacloud.com/help/zh/doc-detail/55811.htm

Do we have such API support in the go sdk?

Thanks.

**Comment by hangzws** [comment]
In branch ipv6, use ProcessObject  api.

**Comment by thomas-lee** [comment]
It is POST request instead of GET request from the doc

use DoAppendObject, RestoreObject?

**Comment by hangzws** [comment]
`func (bucket Bucket) ProcessObject(objectKey string, process string) error {
	params := map[string]interface{}{}
	params["x-oss-process"] = nil
	processData := fmt.Sprintf("%v=%v", "x-oss-process", process)
	data := strings.NewReader(processData)
	resp, err := bucket.do("POST", objectKey, params, nil, data, nil)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	return checkRespCode(resp.StatusCode, []int{http.StatusOK})
}`

**Comment by hangzws** [comment]
`func (bucket Bucket) ProcessObject(objectKey string, process string) error {
	params := map[string]interface{}{}
	params["x-oss-process"] = nil
	processData := fmt.Sprintf("%v=%v", "x-oss-process", process)
	data := strings.NewReader(processData)
	resp, err := bucket.do("POST", objectKey, params, nil, data, nil)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	return checkRespCode(resp.StatusCode, []int{http.StatusOK})
}`

**Comment by thomas-lee** [comment]
thanks, do you have any rough estimation on the release date for the ipv6 branch merged back to master and release?
