### ISSUE TITLE
ContentLanguage Option

### ISSUE THREAD

**Issue by rubensf** [aliyun/aliyun-oss-go-sdk#127]
There's a constant for a `ContentLanguage` [header](https://github.com/aliyun/aliyun-oss-go-sdk/blob/ddc87ec2145f324f91257266e657cd7fa0ff1c8c/oss/const.go#L77), but there's no option for it on [option.go](https://github.com/aliyun/aliyun-oss-go-sdk/blob/5f712e3aeeb39f793fc51feaae8fe1ed71cb4672/oss/option.go). 

Is this missing for some specific reason or was it just forgotten? Would a PR adding it be welcome?

**Comment by rubensf** [comment]
@hangzws mind taking a look at this issue? :)

**Comment by hangzws** [comment]
ok, I will check it.

**Comment by rubensf** [comment]
I just made a PR for it - #128 - do you mind taking a look and approving/merging or requesting changes? :)
