### ISSUE TITLE
如何将整个 Bucket 内所有文件的生命周期设置为统一规则? 

### ISSUE THREAD

**Issue by KISSMonX** [aliyun/aliyun-oss-go-sdk#129]
看了官方的例子, 说有这个功能, 但是没有发现例程, 也没有发现对应的 API.
难道把  prefix 设置为空就表示所有文件?  

另外: 
`oss.BuildLifecycleRuleByDays("rulex", "CSV/", true, 30)`
这个 `rulex` 表示的意思是: 
某个 `Bucket` 的 `CSV` 目录下的所有文件生命周期都是 `30` 天. 这么理解对么. 
如果没建目录呢?

**Comment by king41409** [comment]
prefix 设置为空就表示所有文件oss.BuildLifecycleRuleByDays("rulex", "", true, 30)，oss.BuildLifecycleRuleByDays("rulex", "CSV/", true, 30)表示Bucket 的 CSV 目录下的所有文件生命周期都是 30 天。
