### ISSUE TITLE
断点续传下载错误

### ISSUE THREAD

**Issue by yoyochecknao** [aliyun/aliyun-oss-go-sdk#133]
`err = bucket.DownloadFile("get_and_set_port_status", `"/root/get_and_set_port_status",` 10*1024, oss.Routines(1), oss.Checkpoint(true, ""))
if err != nil {
	fmt.Println("Error3:", err)
	os.Exit(-1)
}`
Error3: Get http://192.168.254.2:8001/pop.php?host=&url=p2sp_http&type=p2sp_http&page=0&model=block&ip=192.168.254.2: dial tcp 192.168.254.2:8001: getsockopt: connection refused
exit status 255

**Comment by hangzws** [comment]
请问一下http://192.168.254.2:8001/ 这个是什么服务？你要上传的文件不是在本地？

**Comment by yoyochecknao** [comment]
不是我启的服务呀，用的就是文档上的demo。。 不知道为啥会出来个内网地址

**Comment by yoyochecknao** [comment]
使用`bucket.GetObjectToFile("get_and_set_port_status", "LocalFile")`就可以正常下载

**Comment by hangzws** [comment]
你换台机器试下吧，这看起来是你的环境问题
