### ISSUE TITLE
How to get object number and total size of a bucket?

### ISSUE THREAD

**Issue by jancco** [aliyun/aliyun-oss-go-sdk#136]
How to get the count and the total size of all objects contained in a bucket?

In theory, one can use ListObjects to achieve that. However, this method would return at most 100 objects each request, so for a bucket containing millions of objects, it becomes almost impossible.

So what's your suggested solution? Thanks!

**Comment by FunriLy** [comment]
@jancco sorry, OSS doesn't provide an interface that can directly count folder sizes. So, you can use ListObjects to achieve this demand, and increase max_key to 1000。
