### ISSUE TITLE
如何取消上传？

### ISSUE THREAD

**Issue by devgogo** [aliyun/aliyun-oss-go-sdk#153]
`bucket.PutObjectFromFile(filepath.Base(file), file)` 一个大文件，但是因为某些原因需要取消上传，如何取消上传呢？
场景：
并行上传一批文件，需要全部成功，如果某一个失败了，则取消其他的。

**Comment by coderall** [comment]
（1）大文件上传可以采用 multipart 方式，如果分片没有全部上传完成，中间可以Abort
（2）上传一批文件，需要全部成功，如果某一个失败了，则取消其他的，这个逻辑需要业务自己实现

**Comment by devgogo** [comment]
> （1）大文件上传可以采用 multipart 方式，如果分片没有全部上传完成，中间可以Abort
> （2）上传一批文件，需要全部成功，如果某一个失败了，则取消其他的，这个逻辑需要业务自己实现

@coderall 
第1点和我的业务场景关系不大，第2点需要这个库实现请求 `context.Context`

**Comment by jan4984** [comment]
2020年都快过完了，go的库还不支持context？阿里云这是店大欺客啊
