### ISSUE TITLE
如何获得上传后文件的url？

### ISSUE THREAD

**Issue by liu0fanyi** [aliyun/aliyun-oss-go-sdk#160]
没找到方法能够获得上传后文件的url，getobject和getobjectmeta和getobjectmetadetail，也都找不到url信息。。。

**Comment by hangzws** [comment]
url就是http://$bucket.$endpoit/$object，是很明确的，不需要api返回

**Comment by FunriLy** [comment]
publish-read文件的话，直接拼接路径。
如果想获取临时URL的话，可以用ossutil工具sign命令生成。
