### ISSUE TITLE
对于http: server closed idle connection有什么建议？

### ISSUE THREAD

**Issue by aleafs** [aliyun/aliyun-oss-go-sdk#169]

**Comment by ShevaXu** [comment]
Maybe consider adding {X-,}Idempotency-Key header to make `net/http` retry on these requests, see https://github.com/golang/go/issues/19943

**Comment by aleafs** [comment]
> Maybe consider adding {X-,}Idempotency-Key header to make `net/http` retry on these requests, see [golang/go#19943](https://github.com/golang/go/issues/19943)

Thank you @ShevaXu very much! 
@hangzws Could you pls support this within the client, or make the method [setHeader](https://github.com/aliyun/aliyun-oss-go-sdk/blob/master/oss/option.go#L364) public to give developers more convenience？
