### ISSUE TITLE
CreatedBeforeDate builder method is missing

### ISSUE THREAD

**Issue by mortyccp** [aliyun/aliyun-oss-go-sdk#195]
@

**Comment by hangzws** [comment]
@mortyccp We do not recommend using this method now, you can use other two to build your rules.

**Comment by mortyccp** [comment]
So does this mean that the create before date expiration option is not working for golang sdk? I read from the official docs that it support 2 option for the expiration: after days or created before date. But currently the public api of this sdk is providing an absolute date and after days option. I think this is super misleading. And you improve it?

**Comment by hangzws** [comment]
@mortyccp Thank you for you advise, my last reply was wrong, we plan to add the method in v2.0.1

**Comment by kkuai** [comment]
@mortyccp，Now，the CreatedBeforeDate api is deleted. I suggest you refer to the test func (s *OssClientSuite) TestSetBucketLifecycleNew  in client_test.go
Thank you for your suggestion！
