### ISSUE TITLE
upload progress API

### ISSUE THREAD

**Issue by Liudada** [aliyun/aliyun-oss-go-sdk#21]
希望有接口能获取实时的上传进度，或者添加一个接口可以从外界传入md5值而不用内部ReadAll一遍

**Comment by gengen1988** [comment]
https://github.com/cheggaaa/pb

**Comment by baiyubin** [comment]
您好， SDK计算MD5可以通过(oss.EnableMD5(false))关闭，通过oss.ContentMD5传入自己计算的MD5值。`1.3.0` 版本后SDK支持了进度条功能。
