### ISSUE TITLE
当有大量请求时，会出现大量的ESTABLISHED连接

### ISSUE THREAD

**Issue by thinkerchi** [aliyun/aliyun-oss-go-sdk#22]
由于向OSS发起的请求都是新建一个client和transport，导致当向OSS发起大量请求的时候，会出现大量的ESTABLISHED连接。
当我并发40个GO程的时候，很快就产生了3万多个ESTABLISHED连接，导致其后请求大量失败。
我的解决方法，是将transport的DisbaleKeepAlives置为true,连接就只维持在了50个左右。
建议：
1、可以共用一个client和transport;
2、开启transport的DisableKeepAlive，让transport不再缓存persistConn

**Comment by baiyubin** [comment]
您好，非常感谢您的建议。
- 建议1，已经开发完成，合入了 `1.2.3` 版本；
- 建议2，增加KeepAlive选项，开发中。
