### ISSUE TITLE
oss如何mock单元测试

### ISSUE THREAD

**Issue by geekso001** [aliyun/aliyun-oss-go-sdk#232]
oss如何mock返回值？，我找了阿里云的官方文档没有找到，我业务代码都写好了，在单元测试时，如何不改变业务代码的情况下，像httpmock插件那样在单元测试方法中定义返回值。

**Comment by geekso001** [comment]
已解决

**Comment by chrislinan** [comment]
> 已解决

请问你是怎么解决的啊 ？
@geekso001

**Comment by geekso001** [comment]
用httpmock解决
github.com/jarcoal/httpmock
