### ISSUE TITLE
PutObject 上传成功后 返回的HTTP Response为何不暴露出来，只是判断成功与否吗？

### ISSUE THREAD

**Issue by BeatsKitano** [aliyun/aliyun-oss-go-sdk#238]
func (bucket Bucket) PutObject(objectKey string, reader io.Reader, options ...Option) error {
	opts := addContentType(options, objectKey)

	request := &PutObjectRequest{
		ObjectKey: objectKey,
		Reader:    reader,
	}
	resp, err := bucket.DoPutObject(request, opts)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

！！！！！！！！！！！！！！！！！！！！！！！！！！！！
       resp.Body 没有任何内容吗
 
	return err
}

**Comment by kkuai** [comment]
可以用GetResponseHeader这个option来获取返回的header，比如：

var respHeader http.Header
err := bucket.PutObject(objectName, reader,oss.GetResponseHeader(&respHeader))
