### ISSUE TITLE
Please add a license file to the project

### ISSUE THREAD

**Issue by harshavardhana** [aliyun/aliyun-oss-go-sdk#245]
There are no license files in the project, not is it explicitly mentioned what is the license for this project. 

We may have to remove support for minio gateway for aliyun OSS if there are no license files found in this library. 

https://github.com/minio/minio/blob/master/cmd/gateway/oss/gateway-oss.go

**Comment by harshavardhana** [comment]
OSS gateway is now scheduled for removal on MinIO project, please respond back here with an updated license file in this repo to avoid this. If not this gateway implementation shall be removed.

**Comment by harshavardhana** [comment]
It is removed from the MinIO minio/minio#9390

**Comment by jhagege** [comment]
Hi @harshavardhana , there is a MIT license in the repository, see here: https://github.com/aliyun/aliyun-oss-go-sdk/blob/master/LICENSE
Can you please bring back support in MinIO ? 
Thanks much.

**Comment by franklouwers** [comment]
Hi @jhagege There is now an MIT license indeed. However, the README.md specifies an Apache 2.0 license. Could you please change the README.md if indeed the intention is to be MIT licensed

**Comment by vimagick** [comment]
OSS gateway was removed: https://github.com/minio/minio/releases/tag/RELEASE.2020-04-22T00-11-12Z
