### ISSUE TITLE
go get fail 

### ISSUE THREAD

**Issue by housemea** [aliyun/aliyun-oss-go-sdk#297]
执行
```
go get -u -v github.com/aliyun/aliyun-oss-go-sdk/oss@master
```
显示如下提示：
```
go get: github.com/aliyun/aliyun-oss-go-sdk@v1.9.9-0.20210826023913-57e9c1c1894e: parsing go.mod:
        module declares its path as: github.com/aliyun/aliyun-oss-go-sdk/oss
                but was required as: github.com/aliyun/aliyun-oss-go-sdk
```

**Comment by akazwz** [comment]
执行
`go get github.com/aliyun/aliyun-oss-go-sdk/oss@v2.1.10`
指定2.1.10版本可行,这个没有遵循mod 的版本规范导致有很多问题,下载下来也是
incompatible
`aliyun-oss-go-sdk@v2.1.10+incompatible`

**Comment by akazwz** [comment]
> 执行
> 
> ```
> go get -u -v github.com/aliyun/aliyun-oss-go-sdk/oss@master
> ```
> 
> 显示如下提示：
> 
> ```
> go get: github.com/aliyun/aliyun-oss-go-sdk@v1.9.9-0.20210826023913-57e9c1c1894e: parsing go.mod:
>         module declares its path as: github.com/aliyun/aliyun-oss-go-sdk/oss
>                 but was required as: github.com/aliyun/aliyun-oss-go-sdk
> ```

执行
`go get github.com/aliyun/aliyun-oss-go-sdk/oss@v2.1.10`
指定2.1.10版本可行,这个没有遵循mod 的版本规范导致有很多问题,下载下来也是
incompatible
`aliyun-oss-go-sdk@v2.1.10+incompatible`

**Comment by housemea** [comment]
> > 执行
> > ```
> > go get -u -v github.com/aliyun/aliyun-oss-go-sdk/oss@master
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 显示如下提示：
> > ```
> > go get: github.com/aliyun/aliyun-oss-go-sdk@v1.9.9-0.20210826023913-57e9c1c1894e: parsing go.mod:
> >         module declares its path as: github.com/aliyun/aliyun-oss-go-sdk/oss
> >                 but was required as: github.com/aliyun/aliyun-oss-go-sdk
> > ```
> 
> 执行
> `go get github.com/aliyun/aliyun-oss-go-sdk/oss@v2.1.10`
> 指定2.1.10版本可行,这个没有遵循mod 的版本规范导致有很多问题,下载下来也是
> incompatible
> `aliyun-oss-go-sdk@v2.1.10+incompatible`

go.mod 里的模块名称又改回去了，哎，太难了，哪位大佬来好好规划一下吧

**Comment by wonko** [comment]
Can a new release be made with the fix in there? This will allow for automated tools to pick up the correct version with the correct go.mod.

**Comment by houseme** [comment]
> Can a new release be made with the fix in there? This will allow for automated tools to pick up the correct version with the correct go.mod.

#302

**Comment by houseme** [comment]
天天改 改过来改过去，有人提交代码 也不处理。
