### ISSUE TITLE
Why are the author & license information removed?

### ISSUE THREAD

**Issue by h12w** [aliyun/aliyun-oss-go-sdk#3]
Why do you copy the code from aliyun-beta and import them under you account, instead of transferring it?

Why do you remove the original README.md together with the author information and LICENSE file from the repository?

This is very unprofessional! Please correct the mistake as soon as possible: remove the repository from github.com/aliyun and transfer from github.com/aliyun-beta and retain the author and license information, otherwise I will submit the issue to Github officials.

**Comment by baiyubin** [comment]
thanks for your feedback, already added you to the author list.
