### ISSUE TITLE
如何获取下载进度

### ISSUE THREAD

**Issue by gengen1988** [aliyun/aliyun-oss-go-sdk#30]
我期望获在分片下载方法里取到文件的大小与当前已经传输的字节数。现在的 SDK 推荐怎么做呢？

**Comment by baiyubin** [comment]
您好，`1.3.0` 版本支持了进度条功能，示例请参看[progress_test.go](https://github.com/aliyun/aliyun-oss-go-sdk/blob/master/oss/progress_test.go)。
