### ISSUE TITLE
DownloadFile 的中止

### ISSUE THREAD

**Issue by gengen1988** [aliyun/aliyun-oss-go-sdk#31]
我在制作客户端的下载工具，`Bucket.DownloadFile` 解决了断点续传，是很方便的方法。

但现在的 `Bucket.DownloadFile` 一旦调用后会一直下载完成，我期望在某些时刻（比如网速低时）停止 `Bucket.DownloadFile`。

这种情况如何通过 SDK 实现呢？

**Comment by baiyubin** [comment]
您好，非常抱歉，目前SDK尚未中止下载的方法。
