### ISSUE TITLE
没有生成object 外链的功能,需要自己手动拼接,非常的麻烦

### ISSUE THREAD

**Issue by liushuchun** [aliyun/aliyun-oss-go-sdk#33]

**Comment by liushuchun** [comment]
你好，你们的链接生成部分没有看到example?

**Comment by baiyubin** [comment]
非常感谢您的反馈，该功能已经支持，示例请参看[GitHub](https://github.com/aliyun/aliyun-oss-go-sdk/blob/master/sample/sign_url.go)
