### ISSUE TITLE
使用oss.SetHeader设置header有一定概率会无效。

### ISSUE THREAD

**Issue by liu602348184** [aliyun/aliyun-oss-go-sdk#347]
- windows 10
- golang 1.18
- aliyun-oss-go-sdk v2.2.5
```golang
ops := []oss.Option{oss.SetHeader("content-type", "text/html;charset=utf-8"), oss.ObjectACL(oss.ACLPublicRead)}
err = bucket.PutObject(htmlFileName, strings.NewReader(htmlContent), ops...)
```
我使用上述代码上传一个html对象到oss并设置`content-type`为`text/html;charset=utf-8`，但是这并不总是会按照我期望的呢样，偶尔会发生`content-type`为`application/octet-stream`的情况。

**Comment by yangzong18** [comment]
ops := []oss.Option{oss.ContentType("text/html;charset=utf-8"), oss.ObjectACL(oss.ACLPublicRead)} 或者 ops := []oss.Option{oss.SetHeader("Content-Type","text/html;charset=utf-8"), oss.ObjectACL(oss.ACLPublicRead)} 才是正确的方式

**Comment by yangzong18** [comment]
> * windows 10
> * golang 1.18
> * aliyun-oss-go-sdk v2.2.5
> 
> ```go
> ops := []oss.Option{oss.SetHeader("content-type", "text/html;charset=utf-8"), oss.ObjectACL(oss.ACLPublicRead)}
> err = bucket.PutObject(htmlFileName, strings.NewReader(htmlContent), ops...)
> ```
> 
> 我使用上述代码上传一个html对象到oss并设置`content-type`为`text/html;charset=utf-8`，但是这并不总是会按照我期望的呢样，偶尔会发生`content-type`为`application/octet-stream`的情况。
ops := []oss.Option{oss.ContentType("text/html;charset=utf-8"), oss.ObjectACL(oss.ACLPublicRead)} 或者 ops := []oss.Option{oss.SetHeader("Content-Type","text/html;charset=utf-8"), oss.ObjectACL(oss.ACLPublicRead)} 才是正确的方式
