### ISSUE TITLE
PutObject失败，返回错误里字段都为空

### ISSUE THREAD

**Issue by seayoung1112** [aliyun/aliyun-oss-go-sdk#35]
从美西连美西的endpoint，一百个go routine并发调用同一个oss client，调用bucket.PutObject方法，有很多失败，而且失败返回的err信息是：
`oss: service returned error: StatusCode=0, ErrorCode=, ErrorMessage=, RequestId=`
无法进一步判断问题，是否是错误信息不对？

**Comment by baiyubin** [comment]
非常感谢您的反馈，这种情况一般是发送请求失败；需要更友好的提示，我们已经列入计划。

**Comment by shengdoushi** [comment]
对啊 怎么解决

**Comment by hangzws** [comment]
请升级一下最新版本，如果还有这个问题，请反馈给我们，谢谢！

**Comment by opvexe** [comment]
内存泄漏，怎么关闭oss调用完毕后
