### ISSUE TITLE
V3 version 

### ISSUE THREAD

**Issue by houseme** [aliyun/aliyun-oss-go-sdk#421]
请问这个v3的版本怎么又删除了呢？

https://pkg.go.dev/github.com/aliyun/aliyun-oss-go-sdk/v3?tab=versions

https://pkg.go.dev/github.com/aliyun/aliyun-oss-go-sdk#readme-version

**Comment by wsw0108** [comment]
不晓得他们在搞什么。
```
$ go get -v github.com/aliyun/aliyun-oss-go-sdk
go: github.com/aliyun/aliyun-oss-go-sdk imports
        github.com/aliyun/aliyun-oss-go-sdk/sample imports
        github.com/aliyun/aliyun-oss-go-sdk/oss: cannot find module providing package github.com/aliyun/aliyun-oss-go-sdk/oss
```

v3可以get，但是用不了
````
$ go get -v github.com/aliyun/aliyun-oss-go-sdk/v3
go: added github.com/aliyun/aliyun-oss-go-sdk/v3 v3.0.0
```

**Comment by houseme** [comment]
> 不晓得他们在搞什么。
> 
> ```
> $ go get -v github.com/aliyun/aliyun-oss-go-sdk
> go: github.com/aliyun/aliyun-oss-go-sdk imports
>         github.com/aliyun/aliyun-oss-go-sdk/sample imports
>         github.com/aliyun/aliyun-oss-go-sdk/oss: cannot find module providing package github.com/aliyun/aliyun-oss-go-sdk/oss
> ```
> 
> v3可以get，但是用不了
> 
> ```
> $ go get -v github.com/aliyun/aliyun-oss-go-sdk/v3
> go: added github.com/aliyun/aliyun-oss-go-sdk/v3 v3.0.0
> ```
> ```

真想自己fork一个来用了

**Comment by houseme** [comment]
@huiguangjun @yangzong18 大佬，v3版本准备支持 `go module` 模式吗？目前发布新版本又删除，这体验太差了。期待支持有 `go.mod` 风格的版本，如果大佬没时间处理，社区同学可以来贡献。

**Comment by huiguangjun** [comment]
近期会在 v3上 把 go.mod 加上

**Comment by houseme** [comment]
> 近期会在 v3上 把 go.mod 加上

 期待，有预估时间点吗？ @huiguangjun
