### ISSUE TITLE
ContentLength选项不生效

### ISSUE THREAD

**Issue by zhangyoufu** [aliyun/aliyun-oss-go-sdk#425]
上传Object时，通过Content-Length头部指定Object大小，超过指定大小的部分被丢弃，未达指定大小返回错误。

SDK中包装了`oss.ContentLength()`选项，但是实际使用中发现没有生效。在`Conn.handleBody`函数中存在几个问题：
1. 传入的 `body` 为 `*os.File` 情况下，对应的文件不一定是常规文件，取 `fInfo.Size()` 可能无意义，`GetReaderLen` 应加入判断 `fInfo.Mode & syscall.S_IFMT == syscall.S_IFREG`
2. 传入的 `body` 为 `*os.File` 情况下，客户端提供的 `reader` 不一定在文件开头，不一定是想要上传整个文件，此处取整个文件的大小可能导致非预期的结果
3. `ContentLength()` 选项虽然在 `headers` 中传入，但是并没有被设置到 `req.ContentLength` 上
4. 极端情况下，客户端可能会传入 `oss.ContentLength(0)`，但是 `req.ContentLength == 0` 在标准库中有特殊含义（见 https://github.com/golang/go/blob/dc094f9c9613a2a8ed24ace1b5416170aa3a334b/src/net/http/request.go#L1502-L1512 ），SDK 这边需要做特殊处理（`req.Body = http.NoBody`）

SDK相关代码：
https://github.com/aliyun/aliyun-oss-go-sdk/blob/2bc58741fa507528ff70b501e7e881a92f88ce3e/oss/conn.go#L458-L468
https://github.com/aliyun/aliyun-oss-go-sdk/blob/2bc58741fa507528ff70b501e7e881a92f88ce3e/oss/utils.go#L452-L477

测试用例：（预期是PutObject报错，实际上没有报错，创建了大小为0的Object）
```go
package main

import (
    "log"
    "os"

    "github.com/aliyun/aliyun-oss-go-sdk/oss"
)

func getOssBucket() *oss.Bucket {
    provider, err := oss.NewEnvironmentVariableCredentialsProvider()
    if err != nil {
        log.Fatal(err)
    }
    ossClient, err := oss.New(os.Getenv("OSS_ENDPOINT"), "", "", oss.SetCredentialsProvider(&provider))
    if err != nil {
        log.Fatal(err)
    }
    ossBucket, err := ossClient.Bucket(os.Getenv("OSS_BUCKET"))
    if err != nil {
        log.Fatal(err)
    }
    return ossBucket
}

func main() {
    bucket := getOssBucket()
    r, w, _ := os.Pipe()
    w.Close()
    err := bucket.PutObject("test", r, oss.ContentLength(1))
    if err != nil {
        log.Printf("PutObject: %v", err)
    }
    hdr, err := bucket.GetObjectDetailedMeta("test")
    if err != nil {
        log.Printf("HeadObject: %v", err)
    }
    log.Print(hdr)
}
```

**Comment by huiguangjun** [comment]
在 c8e9439368e30671dd8bb871282fbc9cdc526635 上修复

可以参考 这个方式使用 
https://github.com/aliyun/aliyun-oss-go-sdk/pull/431/commits/8029f967d8d0f33a801cb88a41535610f65c2db2#diff-62ac287d0ebff9c316b1a090195b6263ee72e23f24044db0e0d3e0b0defbc375R6650

**Comment by zhangyoufu** [comment]
@huiguangjun 

如果你们只打算支持通过`GetReaderLen()`获得长度，那就应该删除`oss.ContentLength(length int64)`这个Option，目前它是no-op。

> `req.ContentLength == 0` 在标准库中有特殊含义

在你们的代码中依然没有修复。`GetReaderLen()` 返回 0 时，`req.ContentLength` 被设置为 0 是不充分的，必须确保 `req.Body = nil` 才表示 `Content-Length: 0`
