### ISSUE TITLE
可不可以直接支持下go1.20向上的版本呢

### ISSUE THREAD

**Issue by lb151** [aliyun/aliyun-oss-go-sdk#441]
希望更新下，可以直接支持go1.20以上的版本，要不然还得兼容模式

**Comment by huiguangjun** [comment]
可以使用 oss go sdk v2 版本，具体信息，可以参考 文档 https://github.com/aliyun/alibabacloud-oss-go-sdk-v2/blob/master/DEVGUIDE-CN.md
