### ISSUE TITLE
[BUG] RestoreObject 无法一次性设置过期时间

### ISSUE THREAD

**Issue by shuqingzai** [aliyun/aliyun-oss-go-sdk#442]
根据文档 [请求参数](https://help.aliyun.com/zh/oss/developer-reference/restoreobject?spm=a2c4g.11186623.0.0.48ec7237O3IW2m#section-xu3-y33-e73) 是可以为 归档存储类型（Archive）设置解冻天数，取值范围为1~7，单位为天，我使用 aliCli 工具测试也是可以的

但是 https://github.com/aliyun/aliyun-oss-go-sdk/blob/3804c1371ab84adf9bacf7d940281b3fb39deb75/oss/bucket.go#L824 并未提供设置日期的参数，尝试使用 RestoreObjectDetail 设置参数会响应报错，因为其内部会设置 `JobParameters.Tier` 参数，归档存储类型（Archive）并不支持该参数，导致报错，参考: https://github.com/aliyun/aliyun-oss-go-sdk/blob/3804c1371ab84adf9bacf7d940281b3fb39deb75/oss/bucket.go#L837-L840

按照 https://github.com/aliyun/aliyun-oss-go-sdk/blob/3804c1371ab84adf9bacf7d940281b3fb39deb75/oss/bucket.go#L813-L823 ，我需要第一次申请解冻后，等待解冻通过再循环重复调用 6 次这个 RestoreObject 才能解冻 7 天，为什么不支持直接设置传递参数？？

**Comment by huiguangjun** [comment]
可以使用 RestoreObjectXML 接口，直接通过xml 方式来 设置过期时间。https://github.com/aliyun/aliyun-oss-go-sdk/blob/master/oss/bucket.go#L869C22-L869C38
