### ISSUE TITLE
go语言并发分片上传，并不能减少上传时间，请问可能会是什么原因呢？

### ISSUE THREAD

**Issue by wangshuai52-tal** [aliyun/aliyun-oss-go-sdk#444]
使用go语言进行分片上传（无并发）一个50MB的视频，大约26秒左右时间；
使用单文件PutObjectFromFile()仍然还是20+秒

使用 分片并发上传，发现并不能减少上传时间，有可能是什么原因导致呢？

并发代码和测试结果如下

```go

// GetCurTimeMs 获取当前时间戳（毫秒）
func GetCurTimeMs1() (int64, string) {
	// 获取当前时间
	now := time.Now()
	nowStr := now.Format("2006-01-02 15:04:05")
	// 获取当前时间的 Unix 时间戳（纳秒）
	timestamp := now.UnixNano()
	// 将纳秒转换为毫秒
	return timestamp / int64(time.Millisecond), nowStr
}

func TestAliYun_MultipartUploadGoroutine(t *testing.T) {
	n, str := GetCurTimeMs1()
	t.Logf("start:%v %v", n, str)

	client, err := oss.New(endpoint, accessKey, secret)
	if err != nil {
		t.Log(err)
                return
	}

	bu := "xxx"
	objectKey := "xxx/xxx.mp4"
	filePath := "/Users/wangshuai/go/xxx/xxx/xxx.mp4"

	bucket, err := client.Bucket(bu)
	if err != nil {
		t.Fatalf("bucket err: %v", err)
	}

	chunks, err := oss.SplitFileByPartNum(filePath, 6)
	if err != nil {
		t.Fatalf("split file err: %v", err)
	}

	expires := time.Date(2049, time.January, 10, 23, 0, 0, 0, time.UTC)
	options := []oss.Option{
		oss.MetadataDirective(oss.MetaReplace),
		oss.Expires(expires),
	}

	n, str = GetCurTimeMs1()
	t.Logf("start1:%v %v", n, str)

	imur, err := bucket.InitiateMultipartUpload(objectKey, options...)
	if err != nil {
		t.Fatalf("initiate multipart upload err: %v", err)
	}

	var parts []oss.UploadPart
	wg := sync.WaitGroup{}
	respChan := make(chan oss.UploadPart, len(chunks))

	n, str = GetCurTimeMs1()
	t.Logf("start2:%v %v", n, str)

	for i, v := range chunks {
		wg.Add(1)
		temp := v
		go func(index int, chunk oss.FileChunk) {
			defer wg.Done()
			fd, openErr := os.Open(filePath)
			if openErr != nil {
				t.Logf("open file err: %v", openErr)
				return
			}
			defer fd.Close()
			fd.Seek(temp.Offset, os.SEEK_SET)
			//调用UploadPart方法上传每个分片。
			n, str := GetCurTimeMs1()
			t.Logf("chunk:%vbegin %v %v", index, n, str)

			part, err := bucket.UploadPart(imur, fd, chunk.Size, chunk.Number)
			if err != nil {
				t.Errorf("bucket.UploadPart err: %v index: %v chunk: %v", err, index, chunk)
				return
			}
			respChan <- part

			n, str = GetCurTimeMs1()
			t.Logf("chunk:%vend %v %v", index, n, str)

		}(i, temp)
	}

	wg.Wait()

	close(respChan)

	for part := range respChan {
		parts = append(parts, part)
	}

	if len(parts) == 0 {
		t.Fatalf("parts is empty")
	}

	if len(parts) != len(chunks) {
		t.Fatalf("parts len: %v chunks len: %v", len(parts), len(chunks))
	}

	objectAcl := oss.ObjectACL(oss.ACLPublicRead)

	n, str = GetCurTimeMs1()
	t.Logf("start4:%v %v", n, str)

	cmur, err := bucket.CompleteMultipartUpload(imur, parts, objectAcl)
	if err != nil {
		t.Fatalf("complete multipart upload err: %v", err)
	}
	n, str = GetCurTimeMs1()
	t.Logf("start5:%v% v", n, str)
	t.Logf("cmur :% v", cmur)
}
```
看起来多个chunk是一起结束的，按理来说并发是成功的,但结果很奇怪，时间上没有进行优化

![image](https://github.com/aliyun/aliyun-oss-go-sdk/assets/131736051/beb7a8d1-9093-4783-8a8e-62c743410a62)

**Comment by huiguangjun** [comment]
可以使用 oss go sdk v2版，它提供了丰富的上传，下载类接口。具体可以参考 [上传下载接口对比](
https://github.com/aliyun/alibabacloud-oss-go-sdk-v2/blob/master/DEVGUIDE-CN.md#%E4%B8%8A%E4%BC%A0%E4%B8%8B%E8%BD%BD%E6%8E%A5%E5%8F%A3%E5%AF%B9%E6%AF%94)

**Comment by wangshuai52-tal** [comment]
好的，有机会试一下；现在项目1.17，使用v2需要整个项目语言升级

顺便问一下，我的问题会是带宽问题吗，上传1个和并发分片上传，我看上传传输速度，两个都是 5000字节/s

**Comment by wangshuai52-tal** [comment]
> 好的，有机会试一下；现在项目1.17，使用v2需要整个项目语言升级
> 
> 顺便问一下，我的问题会是带宽问题吗，上传1个和并发分片上传，我看上传传输速度，两个都是 5000字节/s

**Comment by huiguangjun** [comment]
是不是你的上行带宽不够，即使并发，速度也提不上去？
可以使用ossutil probe 命令测试，[指定项目探测]( https://help.aliyun.com/zh/oss/developer-reference/probe-probe-state?spm=a2c4g.11186623.0.0.2fd66fcfo5kQqB#section-zsg-poq-y0u)

**Comment by wangshuai52-tal** [comment]
> 是不是你的上行带宽不够，即使并发，速度也提不上去？ 可以使用ossutil probe 命令测试，[指定项目探测](https://help.aliyun.com/zh/oss/developer-reference/probe-probe-state?spm=a2c4g.11186623.0.0.2fd66fcfo5kQqB#section-zsg-poq-y0u)


您好运行结果如下：
--------------------------------------------------------------------
./ossutil probe --probe-item upload-speed --bucket ********
cpu core count:12
parallel:12,average speed:2072.28(KB/s),current speed:544.00(KB/s),max speed:42912.00(KB/s))s)
parallel:14,average speed:1398.07(KB/s),current speed:2976.00(KB/s),max speed:2976.00(KB/s)
parallel:16,average speed:1789.79(KB/s),current speed:1728.00(KB/s),max speed:3360.00(KB/s)
parallel:18,average speed:1938.76(KB/s),current speed:1504.00(KB/s),max speed:2816.00(KB/s)
parallel:20,average speed:1971.86(KB/s),current speed:3296.00(KB/s),max speed:3296.00(KB/s)
parallel:22,average speed:1932.14(KB/s),current speed:1792.00(KB/s),max speed:3360.00(KB/s)
parallel:24,average speed:2059.03(KB/s),current speed:2304.00(KB/s),max speed:3392.00(KB/s)

suggest parallel is 12, max average speed is 2072.28(KB/s)

213.539436(s) elapsed

-------------------

max average speed is 2072.28(KB/s)；   正好我的问题是50m左右的视频，1个并发度时需要26s左右，当进行多个并发时，时间并没有显著提升；可以确定是我的  服务的 上传带宽 打满（达到单点限制）？

**Comment by huiguangjun** [comment]
从探测数据来看，是客户端环境 到 服务端的上行带宽 2MiB/s 左右，
单连接上传速度已经打满了，加大并发数起不到效果。
