### ISSUE TITLE
请支持go module（都2024年了）

### ISSUE THREAD

**Issue by voidint** [aliyun/aliyun-oss-go-sdk#445]
```shell
go mod init github.com/aliyun/aliyun-oss-go-sdk
```

这很难吗？

**Comment by huiguangjun** [comment]
OSS Go SDK V2（alibabacloud-oss-go-sdk-v2）是对V1（aliyun-oss-go-sdk）代码库的重大改写。
V2是一个全新的版本，基于GO 1.18+构建，简化了底层操作例如身份验证、自动请求重试及错误处理等；提供了灵活友好的参数配置以及丰富的高级接口，例如分页器、传输管理器 、File-like接口等，全面提升了开发效率和体验。

开始使用V2，请参见[alibabacloud-oss-go-sdk-v2开发者指南](https://github.com/aliyun/alibabacloud-oss-go-sdk-v2/blob/master/DEVGUIDE-CN.md)。

从V1升级为V2，请参见[迁移指南](https://github.com/aliyun/alibabacloud-oss-go-sdk-v2/blob/master/DEVGUIDE-CN.md#%E8%BF%81%E7%A7%BB%E6%8C%87%E5%8D%97)。

**Comment by voidint** [comment]
> OSS Go SDK V2（alibabacloud-oss-go-sdk-v2）是对V1（aliyun-oss-go-sdk）代码库的重大改写。 V2是一个全新的版本，基于GO 1.18+构建，简化了底层操作例如身份验证、自动请求重试及错误处理等；提供了灵活友好的参数配置以及丰富的高级接口，例如分页器、传输管理器 、File-like接口等，全面提升了开发效率和体验。
> 
> 开始使用V2，请参见[alibabacloud-oss-go-sdk-v2开发者指南](https://github.com/aliyun/alibabacloud-oss-go-sdk-v2/blob/master/DEVGUIDE-CN.md)。
> 
> 从V1升级为V2，请参见[迁移指南](https://github.com/aliyun/alibabacloud-oss-go-sdk-v2/blob/master/DEVGUIDE-CN.md#%E8%BF%81%E7%A7%BB%E6%8C%87%E5%8D%97)。

这是什么骚操作？😂 阿里云团队是不是有点草率了：
- 即使有V2版本了，也不妨碍V1版本中增加一个`go.mod`文件。
- V2版本不应该和V1版本在一个工程中吗？git branch是拿来干嘛用的？
- 退一万步，V2另起一个工程就另起一个工程吧，在V1的README不给个链接？

**Comment by huiguangjun** [comment]
1）这两个版本的接口相差很大，不适合在原有仓库上发布。
2）README 已经修改，增加了 v2 版本的说明。
