### ISSUE TITLE
go sdk 怎么没generatePresignedUrl？

### ISSUE THREAD

**Issue by goodforever** [aliyun/aliyun-oss-go-sdk#50]
go sdk 怎么没generatePresignedUrl？

**Comment by sugeladi** [comment]
同问？

**Comment by meteormatt** [comment]
现在好像有了？https://github.com/aliyun/aliyun-oss-go-sdk/commit/c89da717a0ef3c7af4a66610d1568ee4251a8118

**Comment by baiyubin** [comment]
非常感谢大家的反馈，从V1.5.0已经支持了。
