### ISSUE TITLE
Test failed: wrong import path

### ISSUE THREAD

**Issue by zhsj** [aliyun/aliyun-oss-go-sdk#56]
https://github.com/aliyun/aliyun-oss-go-sdk/blob/dee3ad30860e06bd1e28e4d16e2d591da8e03552/sample.go

```
import (
	"fmt"
	"sample"
)
```
this import path should be `github.com/aliyun/aliyun-oss-go-sdk/sample`

**Comment by baiyubin** [comment]
Thank you, it has been fixed .
