### ISSUE TITLE
断点续传下载经常性出现下载失败 unexpected EOF 问题

### ISSUE THREAD

**Issue by bryant24** [aliyun/aliyun-oss-go-sdk#64]
使用可断点续传的下载时，文件.temp明明已经下载完了整个内容字节数，程序卡住不动了，cp文件也存在没删除，等了几分钟后，抛出了错误：unexpected EOF，不知是什么原因导致，望修复。

**Comment by baiyubin** [comment]
多谢您的反馈，EOF是网络拥塞造成的错误，此时文件并没有下载完成。请减少并发数，然后重试即可。

**Comment by bryant24** [comment]
我设置的oss.Routine(20),是这个设置多的原因吗？

**Comment by bryant24** [comment]
线上修改了下并发，改为oss.Routine(5)，测试了两天，下载没有再出现上述问题，建议在文档中或注释中注明下最大线程数的限制，谢谢！

**Comment by bryant24** [comment]
你好，这个问题上次我减小并发线程到5后还是会出现同样的问题，只是不是太频繁了，我检查过temp文件数据字节已经全部下载完了，跟原始文件是一样的大小，但是就是不会重命名，cp文件和temp文件都在但是卡到那里不动了，错误日志显示unexpected EOF，希望能再看下原因，并且都是相对大些的文件，谢谢！

**Comment by hangzws** [comment]
应该是请求弱网的情况下络超时了，服务端socket关闭了，客户端还在读写socket导致的问题。

**Comment by hangzws** [comment]
具体参考：https://stackoverflow.com/questions/17714494/golang-http-request-results-in-eof-errors-when-making-multiple-requests-successi
