### ISSUE TITLE
下载失败是否和 oss endpoint 设置有关系？

### ISSUE THREAD

**Issue by tosone** [aliyun/aliyun-oss-go-sdk#75]
https://github.com/aliyun/aliyun-oss-go-sdk/blob/6fe16293d6b7af4f5c2450714c5b4825c8ad040c/oss/conn.go#L531

这里在默认的情况下采用 http 的协议来访问 oss。

我的设置是采用的没有 http 前缀，故默认会采用 http。如果服务商在中间有广告植入，是否会造成 crc 校验失败，最终导致下载失败？

**Comment by hangzws** [comment]
应该不会有这个问题啊，请问你们出现改问题的现象是什么？
