### ISSUE TITLE
Error on ListObjects: Bucket must be addressed using the specified endpoint

### ISSUE THREAD

**Issue by ghost** [aliyun/aliyun-oss-go-sdk#81]
When calling oss.Bucket.ListObjects, it got the following error:
> oss: service returned error: StatusCode=403, ErrorCode=AccessDenied, ErrorMessage=The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint., RequestId=5A408B4B42BD0241CE407E2B

And calling codes are as following:
>bucket, err := factory.GetOssClient().Bucket(name)
>......
>objectMarker := ""
>for {
>    objects, err := bucket.ListObjects(oss.Marker(objectMarker))
>......

Contexts:
1. This error occurs only if regionId = "eu-central-1".
2. The following API can be called successfully (for all regions):
> factory.GetOssClient().ListBuckets(oss.Marker(bucketMarker))

**Comment by hangzws** [comment]
The endpoint you specified may be incorrect. Try to use the newest version, the error output will print the correct endpoint.
