### ISSUE TITLE
The specified key does not exist.

### ISSUE THREAD

**Issue by bgdsh** [aliyun/aliyun-oss-go-sdk#83]
* endpoint: oss-cn-shanghai.aliyuncs.com。
* accessKeyId: 阿里云超级管理员key。
* accessKeySecret: 对应的secret。

* error message: `oss: service returned error: StatusCode=404, ErrorCode=NoSuchKey, ErrorMessage=The specified key does not exist., RequestId=5A44D439888183B3BCB9F742`

**Comment by bgdsh** [comment]
我确定这一对key/secret是有效的，因为我会用它们来生成STS。

**Comment by Lily922** [comment]
请问这个问题有解决吗@bgdsh

**Comment by bgdsh** [comment]
解决了。文件objectKey最前面不要带/。

**Comment by LilyFaFa** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
您好，我看到您close了oss的specified key的问题，请问是怎么解决的？遇到了类似的问题



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    On 01/2/2018 18:00，白国栋[Bain]<notifications@github.com> wrote： 


Closed #83.

**Comment by Lily922** [comment]
谢谢

**Comment by hongdada** [comment]
请问要不要带后缀名啊

**Comment by bgdsh** [comment]
> 请问要不要带后缀名啊

如果你说的是文件的后缀名的话，答案是YES。
