### ISSUE TITLE
get object return ioutil.NopCloser which cause tcp memory page leak

### ISSUE THREAD

**Issue by cssivision** [aliyun/aliyun-oss-go-sdk#85]
`ioutil.NopCloser` use many times in code, for example, get object from bucket, response body wrap with `io.NopCloser` which makes `Close` method not work. 

it's incrediblely unbelievable to leave the tcp connection opening, this should be avoided.

**Comment by hangzws** [comment]
Yes, it is. we will fix this bug in next release.

**Comment by hangzws** [comment]
done
