### ISSUE TITLE
english godoc

### ISSUE THREAD

**Issue by iwanbk** [aliyun/aliyun-oss-go-sdk#87]
Hi,

Thanks for the great library.
Is there a plan to add english docs?

English docs will broaden the user base of this library

Thanks

**Comment by hangzws** [comment]
hi, you can refer to https://www.alibabacloud.com/help/doc-detail/32147.htm?spm=a2c63.p38356.a1.4.54ca2a218lyCvG, it may not be complete, if there is a problem, you can contact us to improve.
