### ISSUE TITLE
AppendObject 是否能增加一个自动往末尾追加的功能？

### ISSUE THREAD

**Issue by shinexia** [aliyun/aliyun-oss-go-sdk#89]
目前要实现分布式环境下往任意文件追加数据的功能，只能先通过GetObjectDetailedMeta获取到长度，然后再追加，请问是否能够提供一个更加方便的API？

**Comment by hangzws** [comment]
append这个动作本身就是顺序的，在分布式场景下建议在上层做好分布式锁

**Comment by hangzws** [comment]
请问一下，你们这边有边读边写的需求么？

**Comment by hangzws** [comment]
如果有边读边写的请求，且这个时候又与超时错误，这种情况容易产生错乱的问题。所以我们不考虑支持这种功能。
