### ISSUE TITLE
go run sample.go no such host exit status 255

### ISSUE THREAD

**Issue by Digital2Slave** [aliyun/aliyun-oss-go-sdk#90]
Endpoint、AccessKeyId、AccessKeySecret、BucketName已经设置。这些值，我同事用java是可以用的。现在，我需要用golang来进行设置。但是，运行示例代码的时候，出现了**no such host exit status 255**的错误。

翻看 [OSS错误响应](https://www.alibabacloud.com/help/zh/doc-detail/32005.htm) 没有错误代码255的解释。

## 运行示例代码

[运行示例](https://help.aliyun.com/document_detail/32144.html?spm=a2c4g.11186623.6.827.jfIxYL)
下载代码文件。从GitHub下载OSS Go SDK的代码。
修改sample/config.go里的Endpoint、AccessKeyId、AccessKeySecret、BucketName配置。
执行go run sample.go。

```
➜  aliyun-oss-go-sdk git:(master) ✗ go run sample.go 
occurred error: Put http://<my-bucket>.<endpoint>/: dial tcp: lookup <my-bucket>.<endpoint>: no such host
exit status 255
```

## 相关信息

```
➜  aliyun-oss-go-sdk git:(master) ✗ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
➜  aliyun-oss-go-sdk git:(master) ✗ go version
go version go1.9.1 linux/amd64
```

**Comment by Digital2Slave** [comment]
我找到原因了。

**Comment by kris-yi** [comment]
是什么原因啊，我也遇到了
